Let's import the NumPy library

In [51]:
import numpy as np

We can reshape NumPy arrays to different structures to best suit our use case

Imagine you have data which contains the first, middle, and last names of your customers, and that all this information is stored in a 1D array

In [52]:
arr = np.array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'])
arr

array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'], dtype='<U6')

In [53]:
arr.size

6

You want to better shape this array so that it has different subarrays for each customer

In [54]:
np.reshape(a = arr, newshape = (2, 3))

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

You can use reshape in various ways depending on what suits your data, as long as the product of the dimensions equals the original size of the array

In [55]:
np.reshape(arr, (3, 2))

array([['Ashok', 'Ravi'],
       ['Kumar', 'Shiela'],
       ['P.', 'Reddy']], dtype='<U6')

In [56]:
np.reshape(arr, (1, 1, 6))

array([[['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy']]], dtype='<U6')

In [57]:
np.reshape(arr, (6, 1, 1))

array([[['Ashok']],

       [['Ravi']],

       [['Kumar']],

       [['Shiela']],

       [['P.']],

       [['Reddy']]], dtype='<U6')

In [58]:
# np.reshape(arr, (1, 2))  # make sure the product of the provided dimensions to the newshape parameter equals the size of the array

What if we don't know how many customers are in our array?

In [59]:
np.reshape(arr, (-1, 3))  # using -1 will automatically calculate the dimension

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

We can transpose NumPy arrays about their axes to 'flip' them around

Imagine the case where you have two rows of data, one showing the names of various products while the second their price

In [60]:
mat = np.array([['Apple', 'Bread', 'Cheese'], ['Rs. 120', 'Rs. 20', 'Rs. 150']])
mat

array([['Apple', 'Bread', 'Cheese'],
       ['Rs. 120', 'Rs. 20', 'Rs. 150']], dtype='<U7')

In [61]:
mat.shape

(2, 3)

Perhaps we would prefer to show this so that each list contains a product and its price. We can achieve this by transposing the array.

In [62]:
mat.T

array([['Apple', 'Rs. 120'],
       ['Bread', 'Rs. 20'],
       ['Cheese', 'Rs. 150']], dtype='<U7')

In [63]:
mat.transpose()

array([['Apple', 'Rs. 120'],
       ['Bread', 'Rs. 20'],
       ['Cheese', 'Rs. 150']], dtype='<U7')

In [76]:
transposed_mat = mat.transpose()
transposed_mat.shape

(3, 2)

We can proceed similarly with arrays of higher dimensions

In [65]:
three_tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [66]:
three_tensor.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [67]:
three_tensor.transpose()

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [68]:
three_tensor.transpose((2, 1, 0))

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [69]:
three_tensor.transpose((1, 0, 2))

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

We can flatten NumPy arrays to one dimension

In [70]:
mat

array([['Apple', 'Bread', 'Cheese'],
       ['Rs. 120', 'Rs. 20', 'Rs. 150']], dtype='<U7')

In [71]:
mat.ravel()

array(['Apple', 'Bread', 'Cheese', 'Rs. 120', 'Rs. 20', 'Rs. 150'],
      dtype='<U7')

In [72]:
mat.flatten()

array(['Apple', 'Bread', 'Cheese', 'Rs. 120', 'Rs. 20', 'Rs. 150'],
      dtype='<U7')

In [73]:
three_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [74]:
three_tensor.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
three_tensor.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])